CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT fk_user_account_role FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE,
    name VARCHAR(255),
    surname VARCHAR(255),
    phone VARCHAR(255),
    date_of_birth DATE,
    CONSTRAINT fk_member_user FOREIGN KEY (user_id) REFERENCES user_account(id)
);

CREATE TABLE membership_plan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    membership_type VARCHAR(255),
    name VARCHAR(255),
    description VARCHAR(255),
    duration_days INTEGER,
    price DOUBLE,
    active BOOLEAN
);

CREATE TABLE subscription (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT,
    plan_id BIGINT NOT NULL,
    start_date DATE,
    end_date DATE,
    status VARCHAR(255),
    CONSTRAINT fk_subscription_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT fk_subscription_plan FOREIGN KEY (plan_id) REFERENCES membership_plan(id)
);

CREATE TABLE training_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    trainer_name VARCHAR(255),
    start_datetime TIMESTAMP,
    end_datetime TIMESTAMP,
    capacity INTEGER,
    status VARCHAR(255)
);

CREATE TABLE session_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT,
    member_id BIGINT,
    status VARCHAR(255),
    created_at TIMESTAMP,
    CONSTRAINT fk_session_registration_session FOREIGN KEY (session_id) REFERENCES training_session(id),
    CONSTRAINT fk_session_registration_member FOREIGN KEY (member_id) REFERENCES member(id)
);
